# Московский авиационный институт (Национальный исследовательский университет)
## Лабораторная работа №4
## "Pandas"
### Выполнила: студентка группы Т12О-101М-20
### Лёдова Кристина Владимировна
### Преподаватель: Поповкин Александр Викторович
### Москва
### 2020 г.

1.Импортитровать Numpy под именем np

In [ ]:
import numpy as np


2.Напечатать версию и конфигурацию

In [ ]:
print(np.__version__)
np.show_config()

1.18.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


3.Создать вектор (одномерный массив) размера 10, заполненный нулями

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4.Создать вектор размера 10, заполненный единицами

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

5.Создать вектор размера 10, заполненный числом 2.5

In [ ]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

6.Как получить документацию о функции numpy.add из командной строки?

С помощью help(np.add)

7.Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [ ]:
arr = np.zeros(10)
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

8.Создать вектор со значениями от 10 до 49

In [ ]:
np.arange(10,50,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

9.Развернуть вектор (первый становится последним)

In [ ]:
np.arange(10,50)[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

10.Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [ ]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

11.Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [ ]:
a = np.array([1,2,0,0,4,0])
a.nonzero()

(array([0, 1, 4]),)

12.Создать массив 3x3x3 со случайными значениями

In [ ]:
np.random.random((3,3,3))

array([[[0.01647597, 0.91211779, 0.8394339 ],
        [0.89965653, 0.22816908, 0.27880282],
        [0.24239585, 0.75300015, 0.23286669]],

       [[0.45031639, 0.61801038, 0.22912274],
        [0.43933303, 0.9711773 , 0.18473938],
        [0.72159566, 0.92391717, 0.61729497]],

       [[0.65384194, 0.54848369, 0.12813303],
        [0.17200768, 0.3197589 , 0.83802338],
        [0.2732729 , 0.63346708, 0.49350199]]])

13.Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [ ]:
arr = np.random.random((10,10))
print (arr)
print('min = ' + str(arr.min()), 'max = ' + str(arr.max()), sep = '\n')

[[0.35837715 0.50615275 0.93325629 0.17431613 0.35337932 0.34476283
  0.8652905  0.15143126 0.55374018 0.61250193]
 [0.26798189 0.46587486 0.43894437 0.74180778 0.25664421 0.20195461
  0.92771172 0.84480201 0.55806951 0.28096984]
 [0.22488111 0.96355402 0.33146813 0.31133611 0.14538736 0.94988858
  0.23527088 0.69581944 0.90006209 0.38536426]
 [0.08126996 0.54255295 0.17184955 0.40540924 0.05701531 0.48301059
  0.6722511  0.07639806 0.99921946 0.532997  ]
 [0.46358511 0.14305861 0.95216948 0.80717305 0.18417056 0.93968055
  0.85401034 0.1950101  0.59334473 0.53936051]
 [0.73679312 0.72162288 0.16360323 0.80194439 0.76813622 0.56789868
  0.16691726 0.01434267 0.03822566 0.08184988]
 [0.57531365 0.65015723 0.63260392 0.37295937 0.96265292 0.57971214
  0.70863172 0.02973973 0.84780648 0.94445919]
 [0.66945494 0.55237786 0.65294375 0.82329442 0.51010808 0.18771206
  0.20351226 0.63902509 0.39274673 0.50087011]
 [0.40428217 0.99984727 0.93648701 0.67349082 0.05511718 0.65648746
  0.77503133

14.Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [ ]:
arr = np.random.random(30)
print (arr)
print(np.average(arr))

[0.35232012 0.4497428  0.25936906 0.5941423  0.22718914 0.13834414
 0.22755639 0.99560596 0.90152589 0.55777472 0.91031549 0.59256257
 0.9532081  0.5976297  0.65605673 0.75781358 0.25403022 0.44810919
 0.58609873 0.98946837 0.81508745 0.21750467 0.8641204  0.30204835
 0.23455104 0.64638892 0.67271102 0.55547762 0.27134915 0.85859825]
0.5628900016124466


15.Создать матрицу с 0 внутри, и 1 на границах

In [ ]:
arr = np.ones((10,10))
arr[1:-1,1:-1] = 0
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

16.Выяснить результат следующих выражений
0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan

In [ ]:
0 * np.nan

nan

In [ ]:
np.nan == np.nan

False

In [ ]:
np.inf > np.nan

False

In [ ]:
np.nan - np.nan

nan

17.Создать 5x5 матрицу с 1,2,3,4 под диагональю

In [ ]:
np.diag(np.arange(1,5), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

18.Создать 8x8 матрицу и заполнить её в шахматном порядке

In [ ]:
arr = np.zeros((8,8))
arr[::2,::2] = 1
arr[1::2,1::2] = 1
arr

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

19.Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [ ]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

20.Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [ ]:
inp = np.array([1,0,0,1]).reshape((2,2))
np.tile(inp,(4,4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])