In [6]:
## Кристина Лёдова
### Студентка группы Т12О-101М-20

###1. Импортировать NumPy под именем np
In [1]:
    import numpy as np

###2. Напечатать версию и конфигурацию

In [2]:
np.version.full_version
Out[2]:
'1.19.2'
In [16]:
np.show_config()
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]

    
###3. Создать вектор (одномерный массив) размера 10, заполненный нулями

In [3]:
np.zeros(10)
Out[3]:
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])


###4. Создать вектор размера 10, заполненный единицами

In [4]:
np.ones(10)
Out[4]:
array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


###5. Создать вектор размера 10, заполненный числом 2.5

In [5]:
np.full(10, 2.5)
Out[5]:
array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])


###6. Как получить документацию о функции numpy.add из командной строки?

help(np.add)


###7. Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [7]:
arr = np.zeros(10)
arr[4] = 1
arr
Out[7]:
array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])


###8. Создать вектор со значениями от 10 до 49

In [8]:
np.arange(10,50,1)
Out[8]:
array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])


###9. Развернуть вектор (первый становится последним)

In [9]:
np.arange(10,50)[::-1]
Out[9]:
array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])


###10. Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [10]:
np.arange(9).reshape(3, 3)
Out[10]:
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])


###11. Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [11]:
a = np.array([1,2,0,0,4,0])
a.nonzero()
Out[11]:
(array([0, 1, 4]),)

###12. Создать массив 3x3x3 со случайными значениями

In [12]:
np.random.random((3,3,3))
Out[12]:
array([[[0.27041347, 0.15822743, 0.93036714],
        [0.01573616, 0.89474847, 0.15990352],
        [0.90171104, 0.37164251, 0.30556662]],

       [[0.99824488, 0.65711962, 0.55215625],
        [0.19615792, 0.90501024, 0.54121882],
        [0.48524004, 0.7898965 , 0.32310731]],

       [[0.25863251, 0.39244234, 0.30790496],
        [0.60006739, 0.79454275, 0.49755317],
        [0.5194008 , 0.3837123 , 0.53815261]]])

###13. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [13]:
arr = np.random.random((10,10))
print('min = ' + str(arr.min()), 'max = ' + str(arr.max()), sep = '\n')
min = 0.0006500657596492099
max = 0.9973419315560469

###14. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [14]:
arr = np.random.random(30)
print(np.average(arr))
0.47917804051469054

###15. Создать матрицу с 0 внутри, и 1 на границах

In [15]:
arr = np.ones((10,10))
arr[1:-1,1:-1] = 0
arr
Out[15]:
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

###16. Выяснить результат следующих выражений
0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan


In [16]:
0 * np.nan
Out[16]:
nan
In [17]:
np.nan == np.nan
Out[17]:
False
In [18]:
np.inf > np.nan
Out[18]:
False
In [19]:
np.nan - np.nan
Out[19]:
nan


###17. Создать 5x5 матрицу с 1,2,3,4 под диагональю

In [20]:
np.diag(np.arange(1,5), k=-1)
Out[20]:
array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])


###18. Создать 8x8 матрицу и заполнить её в шахматном порядке

In [21]:
arr = np.zeros((8,8))
arr[::2,::2] = 1
arr[1::2,1::2] = 1
arr
Out[21]:
array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])


###19. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [22]:
np.unravel_index(100,(6,7,8))
Out[22]:
(1, 5, 4)


###20. Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [23]:
inp = np.array([1,0,0,1]).reshape((2,2))
np.tile(inp,(4,4))
Out[23]:
array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])


SyntaxError: invalid syntax (<ipython-input-6-32aa6c32fc11>, line 5)