# Московский авиационный институт (Национальный исследовательский университет)
## Лабораторная работа №3
## "Numpy"
### Выполнила: студентка группы Т12О-101М-20
### Лёдова Кристина Владимировна
### Преподаватель: Поповкин Александр Викторович
### Москва
### 2020 г.

In [ ]:
import numpy as np

1.Перемножить матрицы 5x3 и 3x2




In [ ]:
a = np.random.randint(5, size=(5,3))
aa = np.random.randint(5, size=(3,2))
np.dot(a, aa)

array([[13, 11],
       [22,  8],
       [ 8, 16],
       [23, 19],
       [ 5,  1]])


2.Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [ ]:
a = np.arange(11)
a[(a >3 ) & (a < 8)] *= -1
a

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])


3.Создать 5x5 матрицу со значениями в строках от 0 до 4

In [ ]:
np.tile(np.arange(5), 5).reshape(5,5)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

4.Есть генератор, сделать с его помощью массив

In [ ]:
def gen(n):
    for i in range(n):
        yield i
np.fromiter(gen(10), np.int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

5.Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [ ]:
np.linspace(0, 1, 11, endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

6.Отсортировать вектор

In [ ]:
a = np.random.random(10)
a.sort()
print(a)

[0.09335465 0.29349002 0.29833375 0.33433558 0.3913883  0.55942293
 0.66432208 0.70750349 0.72033177 0.8437621 ]


7.Проверить, одинаковы ли 2 numpy массива

In [ ]:
n = np.random.randint(0,5,5)
m = np.random.randint(0,5,5)
compare = np.allclose(n,m)
print(n, m)
print(compare)

[0 2 2 2 3] [0 4 2 2 4]
False


8.Сделать массив неизменяемым

In [ ]:
a = np.arange(10)
a.flags.writeable = False
a[0] = 1

ValueError: ignored

9.Дан массив 10x2 (точки в декартовой системе координат), преобразовать в полярную

In [ ]:
coordinates = np.random.random((10, 2))

x, y = coordinates[:, 0], coordinates[:, 1]

radius = np.sqrt(x**2 + y**2)
angle = np.arctan2(y, x)

np.array([radius, angle])

array([[0.2792075 , 0.81598988, 0.57857971, 0.73731942, 1.20974204,
        0.57104797, 0.71965185, 0.75768277, 0.8948797 , 0.54684512],
       [0.9397822 , 1.28150887, 1.42899992, 1.33525099, 0.80979144,
        0.69792744, 1.52220286, 0.74415362, 0.21134853, 0.50667997]])

10.Заменить максимальный элемент на ноль

In [ ]:
a = np.arange(20)
a[max(a)] = 0
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18  0]


11.Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [ ]:
a = np.zeros((6,6), [('x',float),('y',float)])
a['x'], a['y'] = np.meshgrid(np.linspace(0,1,6), np.linspace(0,1,6))
print(a)

[[(0. , 0. ) (0.2, 0. ) (0.4, 0. ) (0.6, 0. ) (0.8, 0. ) (1. , 0. )]
 [(0. , 0.2) (0.2, 0.2) (0.4, 0.2) (0.6, 0.2) (0.8, 0.2) (1. , 0.2)]
 [(0. , 0.4) (0.2, 0.4) (0.4, 0.4) (0.6, 0.4) (0.8, 0.4) (1. , 0.4)]
 [(0. , 0.6) (0.2, 0.6) (0.4, 0.6) (0.6, 0.6) (0.8, 0.6) (1. , 0.6)]
 [(0. , 0.8) (0.2, 0.8) (0.4, 0.8) (0.6, 0.8) (0.8, 0.8) (1. , 0.8)]
 [(0. , 1. ) (0.2, 1. ) (0.4, 1. ) (0.6, 1. ) (0.8, 1. ) (1. , 1. )]]


12.Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [ ]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(C)

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]


13.Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [ ]:
np_int_types = [
    np.uint, np.uint0, np.uint16, np.uint32, np.uint64, np.uint8, np.uintc, np.uintp,
    np.int, np.int0, np.int16, np.int32, np.int64, np.int8, np.intc, np.integer, np.intp,
]
np_float_types = [
    np.float, np.float128, np.float16, np.float32, np.float64,
]

print('For int')
for t in np_int_types:
    type_info = np.iinfo(t)
    print(t, type_info.min, type_info.max)

print('\n','For float')
for t in np_float_types:
    type_info = np.finfo(t)
    print(t, type_info.min, type_info.max, type_info.eps)

For int
<class 'numpy.uint64'> 0 18446744073709551615
<class 'numpy.uint64'> 0 18446744073709551615
<class 'numpy.uint16'> 0 65535
<class 'numpy.uint32'> 0 4294967295
<class 'numpy.uint64'> 0 18446744073709551615
<class 'numpy.uint8'> 0 255
<class 'numpy.uint32'> 0 4294967295
<class 'numpy.uint64'> 0 18446744073709551615
<class 'int'> -9223372036854775808 9223372036854775807
<class 'numpy.int64'> -9223372036854775808 9223372036854775807
<class 'numpy.int16'> -32768 32767
<class 'numpy.int32'> -2147483648 2147483647
<class 'numpy.int64'> -9223372036854775808 9223372036854775807
<class 'numpy.int8'> -128 127
<class 'numpy.int32'> -2147483648 2147483647
<class 'numpy.integer'> -9223372036854775808 9223372036854775807
<class 'numpy.int64'> -9223372036854775808 9223372036854775807

 For float
<class 'float'> -1.7976931348623157e+308 1.7976931348623157e+308 2.220446049250313e-16
<class 'numpy.float128'> -1.189731495357231765e+4932 1.189731495357231765e+4932 1.084202172485504434e-19
<class 'n

14.Напечатать все значения в массиве

In [ ]:
a = np.arange(20)
for i in a:
    print(a[i], end = ' ')

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 

15.Найти ближайшее к заданному значению число в заданном массиве

In [ ]:
a = np.random.randint(5, size = 10)
def find(a, value):
    index = np.abs(a - value).argmin()
    return index
print(a, find(a, 4), sep = '\n')

[1 0 4 0 1 4 3 2 4 1]
2


17.Дан массив (100,2) координат, найти расстояние от каждой точки до каждой

In [ ]:
coordinates = np.random.random((100, 2))

distances = np.zeros((100, 100))

for i in range(100):
    point_first = coordinates[i]
    for j in range(100):
        point_second = coordinates[j]

        distances[i][j] = np.linalg.norm(np.abs(point_first - point_second))

distances

array([[0.        , 0.68203438, 0.4142131 , ..., 0.78686171, 0.43690424,
        0.77456626],
       [0.68203438, 0.        , 0.50633824, ..., 0.56733456, 0.40271821,
        0.32611474],
       [0.4142131 , 0.50633824, 0.        , ..., 0.37380598, 0.10362818,
        0.42446367],
       ...,
       [0.78686171, 0.56733456, 0.37380598, ..., 0.        , 0.36664176,
        0.26994202],
       [0.43690424, 0.40271821, 0.10362818, ..., 0.36664176, 0.        ,
        0.35029035],
       [0.77456626, 0.32611474, 0.42446367, ..., 0.26994202, 0.35029035,
        0.        ]])

18.Преобразовать массив из float в int

In [ ]:
print(np.random.random(10))
np.random.random(10).astype(np.int)

[0.88245308 0.01680379 0.74913079 0.14852826 0.55456676 0.53951836
 0.45871582 0.67471139 0.63919629 0.83595817]


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

19.Дан файл:

1,2,3,4,5
   6,,,7,8
 ,,9,10,11

Как прочитать его?

In [ ]:
with open('./test_file.txt', 'w') as f:
    f.write('1,2,3,4,5\n6,,,7,8\n,,9,10,11')

np.genfromtxt('./test_file.txt', delimiter = ',')

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6., nan, nan,  7.,  8.],
       [nan, nan,  9., 10., 11.]])

20.Каков эквивалент функции enumerate для numpy массивов?

In [ ]:
list(np.ndenumerate(np.arange(10)))

[((0,), 0),
 ((1,), 1),
 ((2,), 2),
 ((3,), 3),
 ((4,), 4),
 ((5,), 5),
 ((6,), 6),
 ((7,), 7),
 ((8,), 8),
 ((9,), 9)]

21.Сформировать 2D массив с распределением Гаусса

In [ ]:
np.random.normal(size=(2, 2))

array([[-0.55747085,  0.36049179],
       [-1.30806863, -1.85716376]])

22.Случайно расположить p элементов в 2D массив

In [ ]:
n = 5
p = 3
a = np.zeros((n,n))
np.put(a, np.random.choice(range(n*n), p, replace=False), 1)
a

array([[0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

23.Отнять среднее из каждой строки в матрице

In [ ]:
a = np.random.randint(5,size = (5,5))
res = a - a.mean(axis = 1, dtype = int)
res

array([[-1,  0, -2,  3,  0],
       [ 2,  1, -2,  3,  1],
       [ 2, -1,  2,  3, -2],
       [ 0,  0, -2,  0, -1],
       [ 1, -1,  2, -1,  2]])

24.Отсортировать матрицу по n-ому столбцу

In [ ]:
a = np.random.randint(0,5,(4,4))
n = 2
print(a, '\n')
print(a[a[:,n].argsort()])

[[4 4 1 2]
 [1 3 1 4]
 [0 4 4 1]
 [2 0 1 1]] 

[[4 4 1 2]
 [1 3 1 4]
 [2 0 1 1]
 [0 4 4 1]]


25.Определить, есть ли в 2D массиве нулевые столбцы

In [ ]:
a = np.random.randint(0,3,(4,4))
print(a)
print((~a.any(axis=0)).any())

[[1 1 1 0]
 [1 0 0 0]
 [2 0 2 2]
 [1 1 0 1]]
False


26.Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

In [ ]:
a = np.ones(10)
b = np.random.randint(0,len(a),20)
a += np.bincount(b, minlength=len(a))
print(a)

[3. 6. 4. 3. 1. 3. 1. 3. 3. 3.]


27.Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

In [ ]:
width, height = 16, 16
pixel_colors = np.random.randint(0, 2, (height, width, 3)).astype(np.ubyte)
pixel_colors_as_vector = pixel_colors.reshape((height*width, 3))
uniq_colors = np.unique(pixel_colors_as_vector, axis=0)
len(uniq_colors)

8

28.Дан четырехмерный массив, посчитать сумму по последним двум осям

In [ ]:
A = np.random.randint(0,10, (3,3,3,3))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print (A)
print(sum)

[[[[1 7 6]
   [5 7 9]
   [7 1 7]]

  [[2 2 1]
   [8 8 4]
   [7 4 1]]

  [[1 3 0]
   [5 0 0]
   [2 2 8]]]


 [[[9 5 5]
   [7 9 4]
   [1 8 1]]

  [[3 4 0]
   [5 8 1]
   [4 7 2]]

  [[8 2 8]
   [6 2 4]
   [6 9 8]]]


 [[[1 2 5]
   [1 6 0]
   [4 4 9]]

  [[0 3 0]
   [6 1 3]
   [8 2 3]]

  [[0 4 3]
   [4 4 8]
   [2 1 2]]]]
[[50 37 21]
 [49 34 53]
 [32 26 28]]


29.Найти диагональные элементы произведения матриц

In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(0,10,(3,3))
np.diag(np.dot(a, b))

array([50, 54, 80])