# Московский авиационный институт (Национальный исследовательский университет)
## Лабораторная работа №4
## "Pandas"
### Выполнила: студентка группы Т12О-101М-20
### Лёдова Кристина Владимировна
### Преподаватель: Поповкин Александр Викторович
### Москва
### 2020 г.

In [ ]:
import numpy as np


1.Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [ ]:
a = np.array([1,2,3,4,5])

zero = np.zeros(len(a) + (len(a)-1)*3)
print(zero)
zero[::4] = a
print(zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


2.Поменять 2 строки в матрице

In [ ]:
A = np.arange(25).reshape(5,5)
print(A, '\n')
A[[0,1]] = A[[1,0]]
print(A)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


3.Рассмотрим набор из 10 троек, описывающих 10 треугольников (с общими вершинами), найти множество уникальных отрезков, составляющих все треугольники

In [ ]:
set_of_points = np.random.randint(0,30,(10,3))
a = np.roll(set_of_points.repeat(2,axis=1),-1,axis=1)
a = a.reshape(len(a)*3,2)
a = np.sort(a,axis=1)
b = a.view( dtype=[('p0',a.dtype),('p1',a.dtype)] )
b = np.unique(b)
print(b)

[( 1,  2) ( 1, 19) ( 2, 19) ( 4,  6) ( 4,  8) ( 4, 14) ( 4, 21) ( 4, 22)
 ( 5, 11) ( 5, 21) ( 6,  8) ( 6, 14) (10, 26) (10, 27) (11, 21) (12, 25)
 (12, 27) (15, 18) (15, 27) (18, 21) (18, 27) (19, 19) (19, 29) (21, 21)
 (21, 22) (25, 27) (26, 27)]


4.Дан массив C; создать массив A, что np.bincount(A) == C

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])

np.repeat(np.arange(len(C)), C)

array([1, 1, 2, 3, 4, 4, 6])

5.Дан вектор Z, построить матрицу, первая строка которой (Z[0],Z[1],Z[2]), каждая последующая сдвинута на 1 (последняя (Z[-3],Z[-2],Z[-1]))

In [ ]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


6.Инвертировать булево значение, или поменять знак у числового массива без создания нового

In [ ]:
a = np.random.randint(0,2,10)
print(a)
np.logical_not(a, out=a)
print(a)

[1 0 0 1 1 0 0 0 1 1]
[0 1 1 0 0 1 1 1 0 0]


In [ ]:
a = np.random.randint(-1,2,10)
print(a)
np.negative(a, out=a)
print(a)

[ 1  1 -1  0  0  0 -1  0 -1  0]
[-1 -1  1  0  0  0  1  0  1  0]


7.Посчитать ранг матрицы

In [ ]:
a = np.random.uniform(0,1,(5,5))
rank = np.linalg.matrix_rank(a)
print(a)
print(rank)

[[0.40188774 0.81066028 0.72907637 0.39844312 0.63596089]
 [0.19218887 0.762774   0.31121785 0.89866538 0.98939188]
 [0.81039557 0.82165538 0.45888115 0.45182163 0.54840691]
 [0.82566427 0.78859804 0.52123366 0.18577194 0.32841351]
 [0.69018162 0.10518324 0.92981812 0.32076538 0.75910332]]
5


8.Найти наиболее частое значение в массиве

In [ ]:
Z = np.random.randint(0,10,50)
print(Z)
print(np.bincount(Z).argmax())

[4 2 3 1 2 8 2 3 4 1 9 1 6 3 5 0 6 0 6 6 5 3 3 8 2 0 6 3 3 3 8 3 1 7 0 1 5
 7 8 1 1 6 0 9 4 8 4 4 0 7]
3


9.Извлечь все смежные 3x3 блоки из 10x10 матрицы

In [ ]:
from numpy.lib import stride_tricks

Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0] - n)
j = 1 + (Z.shape[1] - n)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
C

array([[[[2, 4, 3],
         [0, 4, 0],
         [2, 2, 3]],

        [[4, 3, 1],
         [4, 0, 1],
         [2, 3, 3]],

        [[3, 1, 3],
         [0, 1, 3],
         [3, 3, 3]],

        [[1, 3, 3],
         [1, 3, 3],
         [3, 3, 3]],

        [[3, 3, 1],
         [3, 3, 0],
         [3, 3, 4]],

        [[3, 1, 2],
         [3, 0, 2],
         [3, 4, 0]],

        [[1, 2, 2],
         [0, 2, 3],
         [4, 0, 3]],

        [[2, 2, 1],
         [2, 3, 3],
         [0, 3, 0]]],


       [[[0, 4, 0],
         [2, 2, 3],
         [2, 1, 4]],

        [[4, 0, 1],
         [2, 3, 3],
         [1, 4, 0]],

        [[0, 1, 3],
         [3, 3, 3],
         [4, 0, 2]],

        [[1, 3, 3],
         [3, 3, 3],
         [0, 2, 1]],

        [[3, 3, 0],
         [3, 3, 4],
         [2, 1, 3]],

        [[3, 0, 2],
         [3, 4, 0],
         [1, 3, 1]],

        [[0, 2, 3],
         [4, 0, 3],
         [3, 1, 2]],

        [[2, 3, 3],
         [0, 3, 0],
         [1, 2, 2]]],


    

10.Рассмотрим множество матриц (n,n) и множество из p векторов (n,1). Посчитать сумму p произведений матриц (результат имеет размерность (n,1))

In [ ]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
S

array([[200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.]])

11.Дан массив 16x16, посчитать сумму по блокам 4x4

In [ ]:
a = np.ones((16,16))
print(a)
k = 4
b = np.add.reduceat(np.add.reduceat(a, np.arange(0, a.shape[0], k), axis=0),
                                       np.arange(0, a.shape[1], k), axis=1)
print(b)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


12.Найти n наибольших значений в массиве

In [ ]:
a = np.arange(100)
np.random.shuffle(a)
n = 5
print(a[np.argpartition(-a,n)[:n]])

[98 99 97 96 95]


13.Построить прямое произведение массивов (все комбинации с каждым элементом)

In [ ]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = map(len, arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print(cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


14.Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [ ]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[0 2 4 5 6 7]


15.Дана 10x3 матрица, найти строки из неравных значений (например [2,2,3])

In [ ]:
Z = np.random.randint(0,5,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z, '\n')
print(U)

[[0 3 0]
 [0 1 0]
 [3 3 4]
 [4 4 0]
 [1 2 1]
 [3 3 3]
 [0 4 3]
 [3 0 4]
 [1 3 4]
 [0 3 4]] 

[[0 3 0]
 [0 1 0]
 [3 3 4]
 [4 4 0]
 [1 2 1]
 [0 4 3]
 [3 0 4]
 [1 3 4]
 [0 3 4]]


16.Преобразовать вектор чисел в матрицу бинарных представлений

In [ ]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


17.Дан двумерный массив. Найти все различные строки

In [ ]:
Z = np.random.randint(0, 2, (6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 1 0]
 [1 0 1]
 [1 1 1]]


18.Даны векторы A и B, написать einsum эквиваленты функций inner, outer, sum и mul

In [ ]:
A = np.random.random((10,))
B = np.random.random((10,))

np.einsum('i->', A)       # np.sum(A)

4.650693118421243

In [ ]:
np.einsum('i,i->i', A, B) # A * B

array([0.10936029, 0.04207389, 0.14657439, 0.73929255, 0.25607208,
       0.86625257, 0.16140497, 0.24380732, 0.00593783, 0.08774724])

In [ ]:
np.einsum('i,i', A, B)    # np.inner(A, B)

2.6585231340950335

In [ ]:
np.einsum('i,j', A, B)    # np.outer(A, B)

array([[0.10936029, 0.16576242, 0.10965616, 0.17181958, 0.10345752,
        0.21327911, 0.05980974, 0.10967737, 0.00830419, 0.0584683 ],
       [0.02775788, 0.04207389, 0.02783297, 0.04361132, 0.02625963,
        0.0541346 , 0.01518093, 0.02783836, 0.00210777, 0.01484045],
       [0.14617891, 0.22157009, 0.14657439, 0.22966654, 0.13828883,
        0.28508434, 0.07994604, 0.14660274, 0.01109999, 0.07815297],
       [0.47054735, 0.71323023, 0.47182038, 0.73929255, 0.44514932,
        0.9176815 , 0.2573449 , 0.47191163, 0.03573067, 0.25157304],
       [0.2706823 , 0.41028559, 0.27141461, 0.42527793, 0.25607208,
        0.52789616, 0.14803762, 0.2714671 , 0.02055406, 0.14471736],
       [0.44417682, 0.67325921, 0.4453785 , 0.69786093, 0.42020215,
        0.86625257, 0.24292271, 0.44546465, 0.03372824, 0.23747432],
       [0.2951241 , 0.44733315, 0.29592253, 0.46367926, 0.27919463,
        0.5755636 , 0.16140497, 0.29597977, 0.02241003, 0.1577849 ],
       [0.24310248, 0.3684816 , 0.2437601