## Лёдова Кристина Владимировна

## группа Т12О-101М-20

In [1]:
import numpy as np


1.Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [5]:
arr = np.array([1,2,3,4,5])

arr_new = np.zeros(len(arr) + (len(arr)-1)*3)
arr_new[::3+1] = arr
arr_new

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

2.Поменять 2 строки в матрице

In [6]:
A = np.arange(25).reshape(5,5)
print(A, '\n')
A[[0,1]] = A[[1,0]]
print(A)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


3.Рассмотрим набор из 10 троек, описывающих 10 треугольников (с общими вершинами), найти множество уникальных отрезков, составляющих все треугольники

In [7]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)

G

array([( 1, 51), ( 1, 84), ( 3, 49), ( 3, 93), ( 9, 25), ( 9, 88),
       (10, 21), (10, 87), (12, 31), (12, 87), (17, 61), (17, 97),
       (20, 24), (20, 64), (21, 87), (24, 64), (25, 88), (31, 87),
       (48, 65), (48, 91), (49, 93), (51, 84), (61, 97), (65, 91),
       (69, 71), (69, 87), (71, 87), (85, 92), (85, 98), (92, 98)],
      dtype=[('p0', '<i8'), ('p1', '<i8')])

4.Дан массив C; создать массив A, что np.bincount(A) == C

In [8]:
C = np.bincount([1,1,2,3,4,4,6])

np.repeat(np.arange(len(C)), C)

array([1, 1, 2, 3, 4, 4, 6])

5.Посчитать среднее, используя плавающее окно

In [9]:

def moving_average(a, n = 3):
    ret = np.cumsum(a, dtype = float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

print(moving_average(np.arange(10), 3))

[1. 2. 3. 4. 5. 6. 7. 8.]


6.Дан вектор Z, построить матрицу, первая строка которой (Z[0],Z[1],Z[2]), каждая последующая сдвинута на 1 (последняя (Z[-3],Z[-2],Z[-1]))

In [10]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


7.Инвертировать булево значение, или поменять знак у числового массива без создания нового

In [14]:
Z = np.random.randint(0,2,100)
np.logical_not(arr, out = arr)

array([1, 1, 1, 1, 1])

In [15]:
Z = np.random.uniform(-1.0,1.0,100)
np.negative(arr, out=arr)

array([-1, -1, -1, -1, -1])

8.Посчитать ранг матрицы

In [16]:
Z = np.random.uniform(0,1,(10,10))
rank = np.linalg.matrix_rank(Z)
print(rank)

10


9.Найти наиболее частое значение в массиве

In [17]:
Z = np.random.randint(0,10,50)
print(Z)
print(np.bincount(Z).argmax())

[4 2 3 1 2 8 2 3 4 1 9 1 6 3 5 0 6 0 6 6 5 3 3 8 2 0 6 3 3 3 8 3 1 7 0 1 5
 7 8 1 1 6 0 9 4 8 4 4 0 7]
3


10.Извлечь все смежные 3x3 блоки из 10x10 матрицы

In [18]:
from numpy.lib import stride_tricks

Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0] - n)
j = 1 + (Z.shape[1] - n)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
C

array([[[[0, 1, 0],
         [2, 1, 3],
         [2, 2, 3]],

        [[1, 0, 3],
         [1, 3, 2],
         [2, 3, 0]],

        [[0, 3, 3],
         [3, 2, 3],
         [3, 0, 3]],

        [[3, 3, 1],
         [2, 3, 1],
         [0, 3, 0]],

        [[3, 1, 3],
         [3, 1, 3],
         [3, 0, 0]],

        [[1, 3, 2],
         [1, 3, 4],
         [0, 0, 1]],

        [[3, 2, 2],
         [3, 4, 2],
         [0, 1, 2]],

        [[2, 2, 2],
         [4, 2, 1],
         [1, 2, 1]]],


       [[[2, 1, 3],
         [2, 2, 3],
         [2, 0, 4]],

        [[1, 3, 2],
         [2, 3, 0],
         [0, 4, 1]],

        [[3, 2, 3],
         [3, 0, 3],
         [4, 1, 2]],

        [[2, 3, 1],
         [0, 3, 0],
         [1, 2, 1]],

        [[3, 1, 3],
         [3, 0, 0],
         [2, 1, 4]],

        [[1, 3, 4],
         [0, 0, 1],
         [1, 4, 1]],

        [[3, 4, 2],
         [0, 1, 2],
         [4, 1, 4]],

        [[4, 2, 1],
         [1, 2, 1],
         [1, 4, 0]]],


    

11.Рассмотрим множество матриц (n,n) и множество из p векторов (n,1). Посчитать сумму p произведений матриц (результат имеет размерность (n,1))

In [19]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
S

array([[200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.]])

12.Дан массив 16x16, посчитать сумму по блокам 4x4

In [20]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
S

array([[16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.]])

13.Найти n наибольших значений в массиве

In [21]:

Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argpartition(-Z,n)[:n]])

[9998 9999 9996 9995 9997]


14.Построить прямое произведение массивов (все комбинации с каждым элементом)

In [22]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = map(len, arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print(cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


15.Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [24]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[0 2 4 5 6 7]


16.Дана 10x3 матрица, найти строки из неравных значений (например [2,2,3])

In [25]:
Z = np.random.randint(0,5,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z, '\n')
print(U)

[[0 3 0]
 [0 1 0]
 [3 3 4]
 [4 4 0]
 [1 2 1]
 [3 3 3]
 [0 4 3]
 [3 0 4]
 [1 3 4]
 [0 3 4]] 

[[0 3 0]
 [0 1 0]
 [3 3 4]
 [4 4 0]
 [1 2 1]
 [0 4 3]
 [3 0 4]
 [1 3 4]
 [0 3 4]]


17.Преобразовать вектор чисел в матрицу бинарных представлений

In [26]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


18.Дан двумерный массив. Найти все различные строки

In [27]:
Z = np.random.randint(0, 2, (6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 1 0]
 [1 0 1]
 [1 1 1]]


19.Даны векторы A и B, написать einsum эквиваленты функций inner, outer, sum и mul

In [28]:
A = np.random.random((10,))
B = np.random.random((10,))

np.einsum('i->', A)       # np.sum(A)

4.650693118421243

In [29]:
np.einsum('i,i->i', A, B) # A * B

array([0.10936029, 0.04207389, 0.14657439, 0.73929255, 0.25607208,
       0.86625257, 0.16140497, 0.24380732, 0.00593783, 0.08774724])

In [30]:
np.einsum('i,i', A, B)    # np.inner(A, B)

2.6585231340950335

In [31]:
np.einsum('i,j', A, B)    # np.outer(A, B)

array([[0.10936029, 0.16576242, 0.10965616, 0.17181958, 0.10345752,
        0.21327911, 0.05980974, 0.10967737, 0.00830419, 0.0584683 ],
       [0.02775788, 0.04207389, 0.02783297, 0.04361132, 0.02625963,
        0.0541346 , 0.01518093, 0.02783836, 0.00210777, 0.01484045],
       [0.14617891, 0.22157009, 0.14657439, 0.22966654, 0.13828883,
        0.28508434, 0.07994604, 0.14660274, 0.01109999, 0.07815297],
       [0.47054735, 0.71323023, 0.47182038, 0.73929255, 0.44514932,
        0.9176815 , 0.2573449 , 0.47191163, 0.03573067, 0.25157304],
       [0.2706823 , 0.41028559, 0.27141461, 0.42527793, 0.25607208,
        0.52789616, 0.14803762, 0.2714671 , 0.02055406, 0.14471736],
       [0.44417682, 0.67325921, 0.4453785 , 0.69786093, 0.42020215,
        0.86625257, 0.24292271, 0.44546465, 0.03372824, 0.23747432],
       [0.2951241 , 0.44733315, 0.29592253, 0.46367926, 0.27919463,
        0.5755636 , 0.16140497, 0.29597977, 0.02241003, 0.1577849 ],
       [0.24310248, 0.3684816 , 0.2437601